import { SiteHeader } from "@/components/custom/site-header";
import { getSession } from "@/lib/auth";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getSession();

  if (!user) {
    redirect("/signin");
  }

  return (
    <>
      <SiteHeader />
      {children}
    </>
  );
}
